version: "3.3"

services:
  db:
    container_name: imdb_db
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/imdb_data

  web:   
    build: .
    container_name: imdb_web         
    environment:
      DJANGO_SETTINGS_MODULE: 'settings.docker'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/src
    # enviroment:
     


volumes:
  db_volume:
